[homelab]
proxy.homelab       ansible_host=192.168.100.10
streaming.homelab   ansible_host=192.168.100.11
arr.homelab         ansible_host=192.168.100.12
downloader.homelab  ansible_host=192.168.100.13
monitoring.homelab  ansible_host=192.168.100.14
library.homelab     ansible_host=192.168.100.15
cloud.homelab       ansible_host=192.168.100.16

[external]
watchtower          ansible_host=100.86.195.146

[docker_hosts:children]
homelab
external

[router]
router.homelab      ansible_host=192.168.1.159

[pihole]
pihole-raspberry    ansible_host=192.168.1.225

[media]
streaming.homelab
arr.homelab
downloader.homelab
library.homelab

[pihole:vars]
ansible_user=arian