---
firewall_rules:
  - port: 8081
    source: "{{ hostvars['arr.homelab']['ansible_host'] }}"
    comment: "qBittorrent WebUI from arr"
  - port: 8081
    source: "{{ hostvars['proxy.homelab']['ansible_host'] }}"
    comment: "qBittorrent WebUI from proxy"
  - port: 8081
    source: "{{ network_main_lan }}"
    comment: "qBittorrent WebUI from main LAN"
  - port: 8081
    source: "{{ network_netbird }}"
    comment: "qBittorrent WebUI from Netbird"
  - port: 68
    protocol: udp
    comment: "DHCP Client"
