---
- name: Ensure Caddy directories exist
  ansible.builtin.file:
    path: "{{ docker_compose_base_dir }}/proxy/caddy"
    state: directory
    owner: "{{ docker_compose_owner }}"
    group: "{{ docker_compose_group }}"
    mode: "0755"

- name: Deploy Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: "{{ docker_compose_base_dir }}/proxy/caddy/Caddyfile"
    owner: "{{ docker_compose_owner }}"
    group: "{{ docker_compose_group }}"
    mode: "0644"
  notify: Restart caddy
