---
ansible_become_password: "{{ vault_become_password }}"

timezone: "Europe/Zurich"

# Docker user settings
docker_user: "nuggets"
docker_uid: "1000"
docker_gid: "1000"

network_main_lan: "192.168.1.0/24"
network_netbird: "100.86.0.0/16"
network_homelab_subnet: "192.168.100.0/24"
