---
firewall_rules:
  - port: 3000
    source: "{{ network_main_lan }}"
    comment: "Homepage from main LAN"
  - port: 3000
    source: "{{ network_netbird }}"
    comment: "Homepage from Netbird"
  - port: 3000
    source: "{{ hostvars['proxy.homelab']['ansible_host'] }}"
    comment: "Homepage from proxy"
  - port: 3001
    source: "{{ network_main_lan }}"
    comment: "Uptime Kuma from main LAN"
  - port: 3001
    source: "{{ network_netbird }}"
    comment: "Uptime Kuma from Netbird"
  - port: 3001
    source: "{{ hostvars['proxy.homelab']['ansible_host'] }}"
    comment: "Uptime Kuma from proxy"
  - port: 8765
    source: "{{ network_main_lan }}"
    comment: "Speedtest from main LAN"
  - port: 8765
    source: "{{ network_netbird }}"
    comment: "Speedtest from Netbird"
  - port: 8765
    source: "{{ hostvars['proxy.homelab']['ansible_host'] }}"
    comment: "Speedtest from proxy"
  - port: 68
    protocol: udp
    comment: "DHCP Client"
