---
- name: Install common and dev packages
  ansible.builtin.apt:
    name:
      - curl
      - ca-certificates
      - gnupg
      - vim
      - git
    state: present
    update_cache: true

- name: Install qemu-guest-agent
  ansible.builtin.apt:
    name: qemu-guest-agent
    state: present
  when: common_tools_qemu_agent

- name: Enable and start qemu-guest-agent
  ansible.builtin.systemd:
    name: qemu-guest-agent
    enabled: true
    state: started
  when: common_tools_qemu_agent
