---
# playbooks/all.yml

- name: Base configuration
  ansible.builtin.import_playbook: base.yml

- name: Reverse proxy
  ansible.builtin.import_playbook: proxy.yml

- name: Streaming stack
  ansible.builtin.import_playbook: streaming.yml

- name: Arr stack
  ansible.builtin.import_playbook: arr.yml

- name: Downloader stack
  ansible.builtin.import_playbook: downloader.yml

- name: Monitoring stack
  ansible.builtin.import_playbook: monitoring.yml

- name: Firewall rules
  ansible.builtin.import_playbook: firewall.yml

- name: Library stack
  ansible.builtin.import_playbook: library.yml

- name: Pi-hole DNS records
  ansible.builtin.import_playbook: pihole.yml

- name: Backups
  ansible.builtin.import_playbook: backup.yml
