---
# playbooks/all.yml

# noqa: name[play]
- import_playbook: base.yml

# noqa: name[play]
- import_playbook: proxy.yml

# noqa: name[play]
- import_playbook: streaming.yml

# noqa: name[play]
- import_playbook: arr.yml

# noqa: name[play]
- import_playbook: downloader.yml

# noqa: name[play]
- import_playbook: monitoring.yml

# noqa: name[play]
- import_playbook: firewall.yml

# noqa: name[play]
- import_playbook: library.yml

# noqa: name[play]
- import_playbook: pihole.yml

- import_playbook: backup.yml
