---
- name: Deploy Proxy Stack
  hosts: proxy.homelab
  become: true

  pre_tasks:
    - name: Ensure Docker is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

  roles:
    - caddy_config
    - docker_compose
